### ISSUE TITLE
Bower deprecations in ember-cli 4.3

### ISSUE THREAD

**Issue by Windvis** [quaertym/ember-cli-dependency-checker#128]
[ember-cli 4.3](https://github.com/ember-cli/ember-cli/blob/master/CHANGELOG.md#v430-beta1) will include [deprecations](https://github.com/ember-cli/ember-cli/pull/9707) for all bower related apis. It seems that this addon is making use of some of those API's and since it's part of the default blueprint, these deprecations will be triggered when people start updating to the 4.3.

The easiest solution would be to simply drop bower support here and release a major version. Apps that do want the version checking for bower dependencies can stay on the v3 release? Alternatively we can manually replace the APIs with custom node code, so bower is still supported but the deprecations won't get triggered. I'm not sure if it's worth the time investment since I doubt projects on modern Ember are still using bower.

**Comment by quaertym** [comment]
I believe best way forward is to drop bower support.

**Comment by Windvis** [comment]
I think the consensus in [Discord](https://discord.com/channels/480462759797063690/480501885837770763/953754096022728734) was that we can't simply remove it here yet since it's still supported in ember-cli. 

The idea was that we would add some bower detection code, and only then run the bower dependency checking code here. That way the deprecation messages from ember-cli won't be shown in apps that don't use bower.

Maybe it would be better to explicitly show a deprecation warning from this addon as well (if bower is detected), since otherwise it might not be clear that this addon is the cause for those other deprecation messages.

**Comment by SergeAstapov** [comment]
@quaertym do you think #129 follows the spirit of that discussion? cc @Windvis

Also, we can do a major version bump of this package with:
* dropping support for bower
* requiring Node.js 14+ (this addon still has support Node.js 6)
* bump all the dependencies

**Comment by Windvis** [comment]
@SergeAstapov I think #129 is exactly what we needed. Thanks!

**Comment by quaertym** [comment]
@SergeAstapov Thanks for tackling this.
