### ISSUE TITLE
null version detected for bower dependencies

### ISSUE THREAD

**Issue by amk221** [quaertym/ember-cli-dependency-checker#13]
When pulling a bower dependancy from a git url like: git://github.com/amk221/my-thing.git **_#master**_
the dependancy is determined to be 'not installed' (therefore builds fail).
It works without the _#tag_

**Comment by rupurt** [comment]
@amk221 @stefanpenner is there any tooling support for vendoring a dependency or do I just need to put it in the `my_ember_app/vendor` directory manually?
