### ISSUE TITLE
ember-cli org

### ISSUE THREAD

**Issue by stefanpenner** [quaertym/ember-cli-dependency-checker#15]
Not a all required, if you are interested [ember-cli org](https://github.com/ember-cli) now exists now and as this repo provides core functionality you are welcome to transition it to that org. 

I will be sure you continue to maintain existing commits + ownership.

If at this point in time you would prefer not to, this is fine. But if in the future you no-longer want to maintain this project, I will then gladly welcome it on the org.

**Comment by quaertym** [comment]
I prefer to keep it for now.
