### ISSUE TITLE
Installed package is not recognized

### ISSUE THREAD

**Issue by indirect** [quaertym/ember-cli-dependency-checker#17]
I just upgraded to Ember 1.10 beta by adding `"ember": "~1.10.0"` to `bower.json`. I ran `bower install`, and everything installed. But the dependency checker fails when I try to start ember-cli:

```
$ ember s
version: 0.1.4

Missing bower packages: 
Package: ember
  * Specified: ~1.10.0
  * Installed: 1.10.0-beta.3
```

Please recognize packages that are correctly installed and meet the requested dependencies.

(tested on ember-cli-dependency-checker version 0.0.6 and 0.0.7)

**Comment by quaertym** [comment]
Have you tried specifying it as 1.10.0-beta.3 in your bower file?

**Comment by indirect** [comment]
Why would that be required? Bower installed a version that meets my requirement, and now I'm being told "not really".

**Comment by quaertym** [comment]
This line `semver.satisfies('1.10.0-beta.3', '~1.10.0')` returns false and I agree that beta version does not satisfy the stable 1.10.0 version. I guess bower tries to do best match. You can manifest this dependency as "ember": ">1.10.0-beta.1" or open an issue for [bower](https://github.com/bower/bower) or [semver](https://github.com/npm/node-semver).

**Comment by indirect** [comment]
Then please change the message to stop saying "run bower install to install missing dependencies", because that is false.

**Comment by quaertym** [comment]
The current version assumes the manifest is correct.

**Comment by indirect** [comment]
That's not the point; the error message is misleading (and flat out wrong in this case). It's extremely user-hostile to throw an error that says "fix this error by running bower install" but running bower install doesn't fix the error. This is the kind of thing that makes people give up on using Ember at all.

**Comment by quaertym** [comment]
This is going to be handled by another feature. See https://github.com/quaertym/ember-cli-dependency-checker/issues/16.
