### ISSUE TITLE
Checker does not follow node-semver rules for beta versions

### ISSUE THREAD

**Issue by indirect** [quaertym/ember-cli-dependency-checker#19]
My package.json contains this line: `"ember-cli-sass": "^3.0.3",`. Trying to run `ember build` results in this message:

```
Missing npm packages: 
Package: ember-cli-sass
  * Specified: ^3.0.3
  * Installed: 3.1.0-beta

Run `npm install` to install missing dependencies.
```

According to [the node-semver documentation about prereleases](https://github.com/npm/node-semver#prerelease-tags), version `3.1.0-beta` does in fact satisfy the specifier `^3.0.3`. Pretty sure it is right, because `npm install` installed version `3.1.0-beta`. Please either follow the specifier rules used by the package managers or change the error message to explain why you don't follow them and how to fix the problem. The error message says to run `npm install`, and that is just flat out wrong.

**Comment by quaertym** [comment]
Well, this it the node console output:
```
> var semver = require('semver');
undefined
> semver.satisfies('3.1.0-beta', '^3.0.3')
false
> semver.satisfies('3.1.0', '^3.0.3')
true
```
This is using the last released version(4.2.0) of `semver` package. If you think this is a bug then submit an issue to semver package.

**Comment by indirect** [comment]
okay, fine, it doesn't satisfy semver, but that means your error message is completely wrong. npm install doesn't help at all.

**Comment by quaertym** [comment]
The message is there to make you aware of the situation. It is your responsibility as a developer to fix the problem. One way to fix it is targeting stable version without caret `3.0.3`. See this [SO question](http://stackoverflow.com/questions/24602648/npm-update-is-installing-a-beta-version-of-the-module-over-the-stable-version) for little more explanation.

**Comment by indirect** [comment]
The SO question you link to says that `3.1.0-beta` _does satisfy_ `^3.0.3`. If NPM uses `semver` to install packages, why does dependency-checker disagree? If dependency-checker disagrees with NPM, why do you keep the error message that says "run `npm install` to fix this problem"?

**Comment by indirect** [comment]
If the point of this package has nothing to do with `bower install` or `npm install`, and instead simply checks to make sure that `semver.satisfies` always returns true, then please update the error messages to explain that.

**Comment by quaertym** [comment]
If you are really concerned about this, please submit an issue to NPM and bower and link back here. As I said before messaging will probably be fixed by https://github.com/quaertym/ember-cli-dependency-checker/issues/16
