### ISSUE TITLE
Ignore `ember install` command

### ISSUE THREAD

**Issue by xtian** [quaertym/ember-cli-dependency-checker#21]
If possible, this addon should ignore the `ember install` command (as well as `install:npm` and `install:bower`) since that command is used to update dependencies.

**Comment by stefanpenner** [comment]
> If possible, this addon should ignore the ember install command (as well as install:npm and install:bower) since that command is used to update dependencies.

`ember install` is currently fundamentally broken. This issue is invalid, although it is because `ember install` is broken, not because of this project.

**Comment by quaertym** [comment]
@stefanpenner What is broken about `ember install`?

**Comment by stefanpenner** [comment]
It can't possible work, as it attempts to do an `npm install` but if `node_modules` is empty or partial, the ember app may not have the deps required to satisfy this

**Comment by quaertym** [comment]
@stefanpenner Do you have a suggestion to fix this?

**Comment by quaertym** [comment]
@stefanpenner ping

**Comment by stefanpenner** [comment]
tell people to use `npm install && bower install` when doing the initial sync.
