### ISSUE TITLE
Ignore devDependencies when deployed to "production" ?

### ISSUE THREAD

**Issue by foxtree** [quaertym/ember-cli-dependency-checker#27]
Could this be done, possibly, by altering [line 90 of dependency-checker.js](https://github.com/quaertym/ember-cli-dependency-checker/blob/f7ee071a1f0c5a242351c20bd7000c25c62a4a6b/lib/dependency-checker.js#L90) as follows?
```
  var dependencies = this.project.dependencies(undefined,process.env.NODE_ENV==='production');
```

**Comment by stefanpenner** [comment]
i hope you are not deploying ember-cli to production

**Comment by quaertym** [comment]
@foxtree This addon should be used on the development or test machine, deploying it to production server has no meaning.
