### ISSUE TITLE
Warns when dependencies are not installed

### ISSUE THREAD

**Issue by marcioj** [quaertym/ember-cli-dependency-checker#29]
Does make sense to `ember-cli-dependency-checker` warns when `node_modules` or `bower_components` are not present? 
For instance running some ember-cli command in a project without `node_modules` will throw `Error: Cannot find module 'ember-cli/lib/broccoli/ember-app'`. I think we could show a better message like: ```No dependencies installed. Run `npm install` and `bower install` to install missing dependencies```.

This is related to ember-cli/ember-cli#3961, but I think this kind of check belongs here.

Thoughts?

//cc @stefanpenner @quaertym

**Comment by stefanpenner** [comment]
> I think we could show a better message like: No dependencies installed. Run `npm install` and `bower install` to install missing dependencies.

+1 better error message

**Comment by quaertym** [comment]
:+1: from me

**Comment by marcioj** [comment]
Looks like the ember-cli-dependency-checker isn't a direct dependency from ember-cli, actually it's a dependency from [generated apps](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/package.json#L27). 
So add this verification here won't work because if we're able to run dependency-checker that means that node_modules are already installed.
Sorry for the confusion :smile:

**Comment by quaertym** [comment]
:smile: Yep, we totally forgot that. :)
