### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by rwjblue** [quaertym/ember-cli-dependency-checker#30]
Might need to be a 0.1.0 to signify that there are relatively large changes (I'm thinking of the shrinkwrap work), but either way I'd love to have a new version to start testing/playing with.

**Comment by stefanpenner** [comment]
:+1:

**Comment by quaertym** [comment]
I agree, I will be releasing new version tonight.

**Comment by quaertym** [comment]
Version 0.1.0 is released. https://github.com/quaertym/ember-cli-dependency-checker/releases/tag/v0.1.0
