### ISSUE TITLE
transition away from SKIP_DEPENDENCY_CHECKER for linked projects

### ISSUE THREAD

**Issue by stefanpenner** [quaertym/ember-cli-dependency-checker#38]
overall the dependency checking is extremely valuable, except when developing a module  via `npm link`.

Using `SKIP_DEPENDENCY_CHECKER=true` in this scenario is actually an anti-pattern, as it is insufficiently granular.

Let me propose instead, `npm link`'ed modules that do not satisfy the version contraints by default merely warn.

note: https://github.com/quaertym/ember-cli-dependency-checker/blob/master/lib/dependency-checker.js#L31

cc @rwjblue

**Comment by quaertym** [comment]
@stefanpenner How can I detect linked modules?

**Comment by rwjblue** [comment]
This seems fine with me. But I do not want to have the env flag removed as it provides a handy escape hatch for some scenarios.
