### ISSUE TITLE
Deployment instructions confusing / misleading

### ISSUE THREAD

**Issue by Fryie** [quaertym/ember-cli-dependency-checker#41]
As discussed in [this issue](https://github.com/ember-cli/ember-cli/issues/4451), it seems that the deployment steps described in the README are confusing and won't work well. I'd suggest just advising to always delete the node_versions directory.

**Comment by quaertym** [comment]
@Fryie why do you install ember-cli globally on CI server?

**Comment by Fryie** [comment]
How would I be running ```ember version``` on the CI server if ember-cli is not installed? I suggest removing the ```ember version``` instruction from that specific section, it is highly confusing.

**Comment by quaertym** [comment]
OK, how about this:
```
(which ember && ember version) || (rm -rf node_modules/ bower_components/ && npm install && bower install)
```

**Comment by stefanpenner** [comment]
Why is the ember check needed?

**Comment by quaertym** [comment]
I think what @mixonic had in mind was that not installing dependencies again if they are already satisfied. `ember version` is the simplest command that triggers dependency check.

**Comment by mixonic** [comment]
Correct, the intent is to trigger the check of deps against shrinkwrap.json.

I doubt the SW checker is getting a lot of usage on npm 2.x though. Eager to try it out with 3.x

**Comment by Fryie** [comment]
Hm, so in case the dependencies didn't change at all and are still cached (semaphore [does this by default](https://semaphoreci.com/docs/caching-between-builds.html) for example) it would make the build somewhat faster...

You'd still have to run ```ember version``` from ```node_modules/ember-cli/bin/```, though (since that's likely not in the path), so that part of the instruction will need to be changed.

> Some build servers cache the ```node_modules``` folder, so it is possible that your app's dependencies are already installed. In order to verify that the dependencies are not out of date you can use ```node_modules/ember-cli/bin/ember version```, which (if Ember is installed) will check that the dependencies are correct.

And then maybe something about not needing to install a global ember-cli on the CI server and that tests can be run via ```npm run test```.

**Comment by quaertym** [comment]
@Fryie `which ember` checks whether `ember` is installed or not, see my comment above.

**Comment by Fryie** [comment]
but why should ember be in the path on a CI server?

**Comment by stefanpenner** [comment]
> but why should ember be in the path on a CI server?

yes, this also confuses me. it should be self contained in node_modules, so running:

```
npm install
npm run test:ci
```

**Comment by quaertym** [comment]
@stefanpenner So the only way to be sure that all dependencies are satisfied is to remove `node_modules` and reinstall with `npm i`? Then there will be no benefit for caching node_modules for people using `npm-shrinkwrap`.

**Comment by volders-semaphore** [comment]
well, if the folder is cached and a version of ember is installed, then ``node_modules/ember-cli/bin/ember version``` should check the contents of the ```node_modules``` folder against the shrinkwrap - so that might actually work for caching.

**Comment by Fryie** [comment]
well, if the folder is cached and a version of ember is installed, then ```node_modules/ember-cli/bin/ember version``` should check the contents of the ```node_modules``` folder against the shrinkwrap - so that might actually work for caching.

**Comment by quaertym** [comment]
@Fryie Is this better?
```
([ -f node_modules/ember-cli/bin/ember ] && node_modules/ember-cli/bin/ember version) || (rm -rf node_modules/ bower_components/ && npm install && bower install)
```

**Comment by Fryie** [comment]
I think that works, at least on my CI server it does (I didn't add the ```[ -f node_modules/ember-cli/bin/ember ]``` part, but it is somewhat cleaner having it).

**Comment by quaertym** [comment]
Skipping that part results in `No such file or directory` error if `node_modules` does not exist.

**Comment by quaertym** [comment]
For further discussion: https://github.com/quaertym/ember-cli-dependency-checker/pull/42
