### ISSUE TITLE
can't track master

### ISSUE THREAD

**Issue by shaunc** [quaertym/ember-cli-dependency-checker#44]
I have a dependency which I would like to track master branch on github:

    "devDependencies": { ...
      "ember-cli-smenu": "shaunc/ember-smenu"
    }

When I try to install another addon, I can't because dependency check fails.

Perhaps in this and similar cases, you could ignore (or warn) on check?

Alternatively (or in addition), in `.ember-cli` or in own config package, there could be a list of dependencies to skip.

**Comment by quaertym** [comment]
It will work if the target is in the following format:
```json
{
  "ember-cli-smenu": "git://github.com/shaunc/ember-smenu.git#master"
}
```

**Comment by shaunc** [comment]
Ah -- thanks!

[NB .ember-ignore-dependencies would still be a good idea I think]

**Comment by quaertym** [comment]
@shaunc Please close if it is fixed. I feel the need for ignoring dep check but not sure what is the best way to do it.

**Comment by shaunc** [comment]
Sure ... closing. I'll happily create a tracking issue for ignoring (though, the other case I need it for is for "npm link" and you already have an issue for that.)
