### ISSUE TITLE
Warn, don't error if a dependency is the wrong version.

### ISSUE THREAD

**Issue by runspired** [quaertym/ember-cli-dependency-checker#56]
Erroring out on missing dependencies is useful, erroring out on incorrect dependencies is a PITA.  Often a dependency is mismatched because a new version is being trialed, and often it's a more recent version than the one in package.json.  Warning would be much more useful.

**Comment by stefanpenner** [comment]
If a new version is being trailed, the package.json should be updated.  Or linked, both cases work correctly currently 


The hard error is because the system is measurably in a bad state, I would encourage this invariant remain.

**Comment by runspired** [comment]
The current behavior breaks the `ember-update` command for exactly this reason..

**Comment by stefanpenner** [comment]
this is actually why we removed `update`

**Comment by stefanpenner** [comment]
I have plans to create a more standalone installer, as we have plans to do a more constraint based installation in the future. I hope to rectify the check+egg issue as part of that effort.

**Comment by runspired** [comment]
:+1:

**Comment by runspired** [comment]
I would still like to support the "update an addon from a clean install" situation.  Needing to install everything before you can get to work is frustrating, especially when that becomes

- manually modify package.json
- npm install
- ember g <addon-blueprint>

If that was all you wanted to do for the day, it really cuts your time over being able to just do

- ember install <addon>

**Comment by stefanpenner** [comment]
If that is something you want to work on, it would be greatly appreciated :P I don't forsee working on that for quite some time.. :(

**Comment by runspired** [comment]
I'm working on tools for helping maintain addon / app dependencies and facilitate faster scaffolding at the moment.  Whether that will lead to wanting to work on a stand-alone installer, I don't know, but if it does I'll ping you.

**Comment by sglanzer** [comment]
@runspired did your work on this lead anywhere?  I'm doing research before starting a similar effort and I want to make sure the project is based on current information
