### ISSUE TITLE
Release 1.2.0 is causing deprecation warnings

### ISSUE THREAD

**Issue by yads** [quaertym/ember-cli-dependency-checker#58]
Version 1.2.0 is causing the following error

> DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-dependency-checker`

Commit https://github.com/quaertym/ember-cli-dependency-checker/commit/6c05a3316fde10b502baec5555502fd7b3212adf fixes this. Can we get a new release out?

**Comment by rwjblue** [comment]
Agreed.

@quaertym - I would love to get @stefanpenner and/or myself added on NPM so we can help deal with (triage/fix/release/etc) these sorts of urgent issues.

**Comment by quaertym** [comment]
Sorry for the delay, I was on vacation this week.

@rwjblue I'll do asap.

**Comment by rwjblue** [comment]
@quaertym - Awesome, thank you!  Hope vacation was nice 😸
