### ISSUE TITLE
Detect yarn and surface correct error message

### ISSUE THREAD

**Issue by elwayman02** [quaertym/ember-cli-dependency-checker#64]
It would be nice to not have the error message for missing dependencies say to use `npm install` when you're using yarn in that project. Developers who are not familiar with what's going on will just trust the error message instead of realizing that they should actually have run `yarn install`.

**Comment by rwjblue** [comment]
I think this is entangled (somewhat) with https://github.com/quaertym/ember-cli-dependency-checker/issues/62.

**Comment by elwayman02** [comment]
yea, I agree, just wanted to file it as a separate issue since technically there *may* be a way to solve one without solving the other. In practice, though, it probably makes the most sense to resolve both issues at once.
