### ISSUE TITLE
Add ember-cli team to `npm` for releases... 

### ISSUE THREAD

**Issue by rwjblue** [quaertym/ember-cli-dependency-checker#70]
This addon has been *extremely* helpful to all ember-cli users for quite some time.  Since this is somewhat fundamental to newly generated ember-cli applications, I'd like to reduce [bus factor](https://en.wikipedia.org/wiki/Bus_factor) and get a few of the [ember-cli core team members](https://emberjs.com/team/) added to `npm` for releasing updates and fixes. 

The following would be a great start:

```
npm owner add stefanpenner ember-cli-dependency-checker
npm owner add rwjblue ember-cli-dependency-checker
npm owner add turbo87 ember-cli-dependency-checker
```

/cc @quaertym

**Comment by quaertym** [comment]
👍  Great Idea. I did it.
