### ISSUE TITLE
dev dependencies required to be installed before running ember-deploy

### ISSUE THREAD

**Issue by azuruce** [quaertym/ember-cli-dependency-checker#72]
I have dev dependencies such as http-proxy, express in package.json. I can use "npm install --production" to install all production dependencies, but I can't deploy using ember deploy b/c the dependency checker will flag those missing dependencies.

**Comment by Pezmc** [comment]
I'm also having this problem, we moved all testing dependencies into `devDependencies` and ones required to build the project to `dependencies`, but ember-cli-dependency-checker complains that the devDependencies aren't installed and prevents `ember build --prod` from running!

**Comment by rwjblue** [comment]
You can disable this addon via an environment variable, but it is operating as intended (it _should_ be validating both dependencies and devDependencies).

**Comment by rwjblue** [comment]
FWIW, I believe it is `SKIP_DEPENDENCY_CHECKER= true ember build —prod`

**Comment by quaertym** [comment]
Yep, for reference check this [line](https://github.com/quaertym/ember-cli-dependency-checker/blob/master/lib/dependency-checker.js#L36).
