### ISSUE TITLE
Yarn workspaces

### ISSUE THREAD

**Issue by bsvipas** [quaertym/ember-cli-dependency-checker#78]
Hi, it doesn't work correctly with Yarn workspaces... Here is the issues: https://github.com/yarnpkg/yarn/issues/4503 (same as https://github.com/yarnpkg/yarn/issues/4081). All other apps works fine, they search for `node_modules` in root dir instead of current dir if they don't find it, but Ember just search it in current dir...

**Comment by bsvipas** [comment]
I fixed this issue. Right now I need to polish it and I will try to make PR.

**Comment by mblackritter** [comment]
Luckily, until this is resolved, the solution is to just remove ember-cli-dependency-checker. 🙃
