### ISSUE TITLE
Gets confused when dealing with Bower packages installed via Yarn

### ISSUE THREAD

**Issue by wagenet** [quaertym/ember-cli-dependency-checker#79]
https://bower.io/blog/2017/how-to-migrate-away-from-bower/

ember-cli-dependency-checker attempts to validate these packages as npm packages. If they're bower-only packages it will fail due to the missing or incomplete package.json.

**Comment by yjaspar** [comment]
Having the same issue

**Comment by gibso** [comment]
is there any other solution than just uninstalling ember-cli-dependency-checker?

**Comment by Speennaker** [comment]
Having the same issue. But looks like nobody cares!

**Comment by YamunaSubramanian** [comment]
Same issue. Any solution?

**Comment by quaertym** [comment]
Released as [v3.2.0](https://github.com/quaertym/ember-cli-dependency-checker/tree/v3.2.0).
